###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

title: Dylan's Blog
author: Dylan Davis

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Resume: "assets/Redacted.pdf"

################
# --- Logo --- #
################

avatar: "assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  github: DylanDavis1
  linkedin: DylanDavis2

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false

url-pretty: "https://dylandavis1.github.io"
url: "https://dylandavis1.github.io"

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: true
post_search: true

######################################
# --- Colours / background image --- #
######################################

navbar-col: "#404040"
navbar-text-col: "#EAEAEA"
navbar-border-col: "#DDDDDD"
page-col: "#696969"
text-col: "#ffffff"
link-col: "#dad42b"
hover-col: "#dad42b"
footer-col: "#404040"
footer-text-col: "#EAEAEA"
footer-link-col: "#000000"
footer-hover-col: "#dad42b"

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""
#gtm: ""

####################
# --- Comments --- #
####################

#disqus: ""
#fb_comment_id: ""
#commentbox: ""

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
